DATABASE_NAME = "../infra/sqlite/main.db"
SQL_FILE = "../infra/sqlite/start_up.sql"
SQL_FILE_TEST = "../infra/sqlite/start_up.sql"

STARTING_BITCOIN_AMOUNT = 1
WALLETS_LIMIT = 3
TOKEN_HEX_BYTES_NUM = 32
ADMIN_API_KEY = "MELOTI_MOMGERALI_PROGRAMISTI"
FAKE_RATE = 100.0
# NOT_ENOUGH_BITCOIN_IN_ERROR_CODE = 409
# WALLETS_LIMIT_ERROR_CODE = 409
# DOES_NOT_EXIST_ERROR_CODE = 404
# EMAIL_ALREADY_EXIST_ERROR_CODE = 409
# WALLET_PERMISSION_ERROR_CODE = 403
# INVALID_API_KEY_ERROR_CODE = 401
# TRANSACTION_BETWEEN_SAME_WALLET_ERROR_CODE = 405
