DATABASE_NAME = "infra/sqlite/main.db"
SQL_FILE = "./infra/sqlite/start_up.sql"
SQL_FILE_TEST = "../infra/sqlite/start_up.sql"

STARTING_BITCOIN_AMOUNT = 1
WALLETS_LIMIT = 3
TOKEN_HEX_BYTES_NUM = 32

NOT_ENOUGH_BITCOIN_IN_ERROR_CODE = 404
TRANSACTION_BETWEEN_SAME_WALLET_ERROR_CODE = 404
WALLET_PERMISSION_ERROR_CODE = 404
WALLETS_LIMIT_ERROR_CODE = 404
INVALID_API_KEY_ERROR_CODE = 401
DOES_NOT_EXIST_ERROR_CODE = 404
